# Generated by Django 3.0.2 on 2020-01-27 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Clients', verbose_name='Storage')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='NotificationGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('contacts', models.ManyToManyField(to='eldashboard.Contacts')),
            ],
            options={
                'db_table': 'notificationgroups',
            },
        ),
        migrations.CreateModel(
            name='StorageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'storagecategories',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=502)),
                ('clientref', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('received', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Clients')),
                ('notificationgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldashboard.NotificationGroups')),
                ('storage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eldashboard.StorageCategory', verbose_name='Storage')),
            ],
            options={
                'db_table': 'samples',
            },
        ),
    ]
