# Generated by Django 3.0.2 on 2020-02-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address1', models.CharField(max_length=50, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Address 2')),
                ('city', models.CharField(max_length=25)),
                ('postcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(blank=True, default='', max_length=25, null=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(blank=True, default='', max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=25)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Clients')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponumber', models.CharField(max_length=25)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Clients')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='JobSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'jobsamples',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='NotificationGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('contacts', models.ManyToManyField(to='eldashboard.Contacts')),
            ],
            options={
                'db_table': 'notificationgroups',
            },
        ),
        migrations.CreateModel(
            name='ReportTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'reporttypes',
            },
        ),
        migrations.CreateModel(
            name='StorageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'storagecategories',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TestMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('tmnumber', models.CharField(max_length=5)),
                ('decimalplaces', models.IntegerField()),
                ('error', models.FloatField()),
                ('errortype', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('reporttype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eldashboard.ReportTypes')),
            ],
            options={
                'db_table': 'testmethods',
            },
        ),
        migrations.CreateModel(
            name='SampleTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testresult', models.CharField(blank=True, default='', max_length=25)),
                ('testunits', models.CharField(blank=True, default='', max_length=25)),
                ('testdate', models.CharField(blank=True, default='', max_length=25)),
                ('jobsample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.JobSample')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldashboard.Locations')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldashboard.Users')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.TestMethods')),
            ],
            options={
                'db_table': 'sampletests',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clientref', models.CharField(default='', max_length=50)),
                ('batch', models.CharField(blank=True, default='', max_length=50)),
                ('condition', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('received', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Clients')),
                ('notificationgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldashboard.NotificationGroups')),
                ('storage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eldashboard.StorageCategory')),
            ],
            options={
                'db_table': 'samples',
            },
        ),
        migrations.AddField(
            model_name='jobsample',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Sample'),
        ),
        migrations.CreateModel(
            name='JobReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('filepath', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Job')),
            ],
            options={
                'db_table': 'jobreports',
            },
        ),
        migrations.CreateModel(
            name='JobActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('details', models.CharField(max_length=200)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Job')),
            ],
            options={
                'db_table': 'jobactivity',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='jobsamples',
            field=models.ManyToManyField(to='eldashboard.JobSample'),
        ),
        migrations.AddField(
            model_name='job',
            name='notificationgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldashboard.NotificationGroups'),
        ),
    ]
