# Generated by Django 3.0.2 on 2020-01-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='batch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='clientref',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='condition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
