# Generated by Django 3.0.2 on 2020-02-03 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0002_auto_20200129_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='address1',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='address2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clients',
            name='city',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='country',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='clients',
            name='postcode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='state',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Clients', verbose_name='Client'),
        ),
    ]
