# Generated by Django 3.0.2 on 2020-02-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0003_auto_20200203_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='address1',
            field=models.CharField(max_length=50, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='country',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Clients'),
        ),
    ]
