# Generated by Django 3.0.3 on 2020-02-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0003_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreports',
            name='reportno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
