# Generated by Django 3.0.3 on 2020-02-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0004_jobreports_reportno'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='Open', max_length=25),
            preserve_default=False,
        ),
    ]
