# Generated by Django 3.0.2 on 2020-02-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0004_auto_20200203_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
