# Generated by Django 3.0.3 on 2020-02-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0008_auto_20200227_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmethods',
            name='tmnumber',
            field=models.CharField(max_length=15),
        ),
    ]
