# Generated by Django 3.0.2 on 2020-02-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0009_auto_20200204_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
