# Generated by Django 3.0.2 on 2020-02-04 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0010_auto_20200204_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'reporttypes',
            },
        ),
        migrations.CreateModel(
            name='TestMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('tmnumber', models.CharField(max_length=5, verbose_name='TM #')),
                ('decimalplaces', models.IntegerField(verbose_name='Decimal Places')),
                ('relativeError', models.FloatField(verbose_name='Relative Error %')),
                ('absoluteError', models.FloatField(verbose_name='Absolute Error')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('reporttype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eldashboard.ReportTypes', verbose_name='Report Types')),
            ],
            options={
                'db_table': 'testmethods',
            },
        ),
    ]
