# Generated by Django 3.0.3 on 2020-02-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0010_auto_20200227_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='invoiceno',
            field=models.CharField(default='', max_length=25),
        ),
    ]
