# Generated by Django 3.0.3 on 2020-02-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0011_job_invoiceno'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
