# Generated by Django 3.0.2 on 2020-02-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0011_reporttypes_testmethods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmethods',
            name='absoluteError',
        ),
        migrations.RemoveField(
            model_name='testmethods',
            name='relativeError',
        ),
        migrations.AddField(
            model_name='testmethods',
            name='error',
            field=models.FloatField(default=0, verbose_name='Error'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmethods',
            name='errortype',
            field=models.IntegerField(default=0, verbose_name='Error Type'),
            preserve_default=False,
        ),
    ]
