# Generated by Django 3.0.2 on 2020-02-04 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0012_auto_20200204_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponumber', models.CharField(max_length=25)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Clients')),
                ('notificationgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eldashboard.NotificationGroups')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='JobSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Job')),
            ],
            options={
                'db_table': 'jobsamples',
            },
        ),
        migrations.AlterField(
            model_name='sample',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eldashboard.StorageCategory'),
        ),
        migrations.AlterField(
            model_name='testmethods',
            name='decimalplaces',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testmethods',
            name='error',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='testmethods',
            name='errortype',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testmethods',
            name='reporttype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eldashboard.ReportTypes'),
        ),
        migrations.AlterField(
            model_name='testmethods',
            name='tmnumber',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='SampleTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testresult', models.CharField(blank=True, default='', max_length=25)),
                ('testunits', models.CharField(blank=True, default='', max_length=25)),
                ('jobsample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.JobSample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.TestMethods')),
            ],
            options={
                'db_table': 'sampletests',
            },
        ),
        migrations.AddField(
            model_name='jobsample',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Sample'),
        ),
        migrations.CreateModel(
            name='JobReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('filepath', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Job')),
            ],
            options={
                'db_table': 'jobreports',
            },
        ),
        migrations.CreateModel(
            name='JobActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('details', models.CharField(max_length=200)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Job')),
            ],
            options={
                'db_table': 'jobactivity',
            },
        ),
    ]
