# Generated by Django 3.0.3 on 2020-02-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0012_sample_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
