# Generated by Django 3.0.2 on 2020-02-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0013_auto_20200205_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsample',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='jobsamples',
            field=models.ManyToManyField(to='eldashboard.JobSample'),
        ),
    ]
