# Generated by Django 3.0.3 on 2020-02-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0013_auto_20200227_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='clientref',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sample',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
