# Generated by Django 3.0.3 on 2020-05-18 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0017_notificationgroups_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(max_length=100)),
                ('docno', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.Job')),
            ],
            options={
                'db_table': 'jobdata',
            },
        ),
    ]
