# Generated by Django 3.0.3 on 2020-05-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0018_jobdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='ReportTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('filepath', models.CharField(max_length=100)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eldashboard.ReportTypes')),
            ],
            options={
                'db_table': 'reporttemplates',
            },
        ),
    ]
