# Generated by Django 3.0.3 on 2020-05-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0019_auto_20200518_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttemplates',
            name='filepath',
        ),
        migrations.AddField(
            model_name='reporttemplates',
            name='document',
            field=models.FileField(default='', upload_to='report_templates/'),
            preserve_default=False,
        ),
    ]
