# Generated by Django 3.0.3 on 2020-05-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0020_auto_20200519_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='temp_reports/')),
            ],
            options={
                'db_table': 'reportdocs',
            },
        ),
    ]
