# Generated by Django 3.0.3 on 2020-05-19 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eldashboard', '0021_reportdocs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportDocs',
        ),
    ]
